apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: myjenkins
  namespace: demo
spec:
  selector:
    matchLabels:
      app: myjenkins
  replicas: 2 
  template: 
    metadata:
      labels:
        app: myjenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins:latest
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc
